server:
  port: ${APP_PORT:8686}
  servlet.context-path: /

pdf2html:
  # /usr/local/bin/pdf2htmlEX --zoom 1.3
  command: ${PDF2HTML_COMMAND:/usr/local/bin/pdf2htmlEX --zoom 1.3 --quiet 1}
  command-timeout: ${PDF2HTML_COMMAND_TIMEOUT:600s}
  work-dir: ${PDF2HTML_WORK_DIR:/tmp/pdf2html-service}
  max-process: ${PDF2HTML_MAX_PROCESS:15}

spring:
  application:
    name: pdf2html-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB